exp:
    name: "dcase2019_4"

data_loader:
    name: "dcase2019_4.DCASEDataGenerator"
    train:
        data_dir: "/corpora/DCASE2019_task4/dataset/audio/train"
        feature_dir: "/corpora/DCASE2019_task4/features"
        meta_file: "/corpora/DCASE2019_task4/dataset/metadata/train/_train.csv"
        batch_size: 32
    eval:
        data_dir: "/corpora/DCASE2019_task4/dataset/audio/validation"
        feature_dir: "/corpora/DCASE2019_task4/features"
        meta_file: "/corpora/DCASE2019_task4/dataset/metadata/validation/_validation.csv"
        batch_size: 32
        
    unique_labels_fn: "etc/unique_labels.lst"
    label_encoder_fn: "/corpora/DCASE2019_task4/dataset/label_encoder.pkl"
    n_classes: 11
    nfft: 2048
    n_mels: 64
    frame_size_ms: 25
    hop_size_ms: 10
    sampling_rate: 16000
    audio_duration: 0.960

model:
    name: "recurrent.CRNN"
    load_checkpoint_file: "experiments/dcase2019_4/checkpoints/weights.128.92.hdf5"
    learning_rate: 0.00001
    conv_filters: 128
    conv_stride: 1
    filter_size: 8
    rec_layers: 1
    rec_layer_size: 128

trainer:
    name: "simple.SimpleTrainer"
    num_epochs: 100
    verbose_training: True

callbacks:
    ModelCheckpoint:
        monitor: val_loss
        mode: min
        save_best_only: True
        save_weights_only: True
        verbose: True
    EarlyStopping:
        monitor: val_loss
        patience: 10
    ReduceLROnPlateau:
        monitor: val_loss
        factor: 0.1
        patience: 10
        min_lr: 0.000001
    tensorboard_log_dir: logs
    tensorboard_write_graph: True
