exp:
    name: freesound

data_loader:
    name: "freesound.FreesoundDataGenerator"
    data_dir: "/home/aagnone/corpora/freesound-audio-tagging"
    n_classes: 41
    nfft: 2048
    n_mels: 64
    frame_size_ms: 25
    hop_size_ms: 15
    sampling_rate: 16000
    audio_duration: 2
    batch_size: 64

model:
    name: "convolutional.CNN"
    learning_rate: 0.0001

trainer:
    name: "simple.SimpleTrainer"
    num_epochs: 100
    validation_split: 0.20
    verbose_training: True

callbacks:
    ModelCheckpoint:
        monitor: val_loss
        mode: min
        save_best_only: True
        save_weights_only: True
        verbose: True
    EarlyStopping:
        monitor: val_loss
        patience: 10
    ReduceLROnPlateau:
        monitor: val_loss
        factor: 0.1
        patience: 10
        min_lr: 0.000001
    tensorboard_log_dir: logs
    tensorboard_write_graph: True
